#!/bin/bash

if [ $# -eq 0 ] || [ -t 0 ]; then
    >&2 echo "usage: $(basename "$0") <host> [host...] < hash-list.txt"
    exit 1
fi

while read qm_line; do
    for qm in $qm_line; do
        for host in $@; do
            ssh "$host" -t bash -lc "time ipfs pin add --progress $qm"
        done
    done
done
