#!/bin/bash

[ $# -eq 0 ] && { >&2 echo "usage: $0 <search terms>"; exit 1; }

mkdir -p "$HOME/.ytc"

h="$(md5sum <<< "$*" | cut -d' ' -f1)"

_play() {
    if [ -e "$HOME/.ytc/$h"* ]; then
        mpv --vo=null "$HOME/.ytc/$h"*
        exit
    fi
}

_play # attempt to play cached file and exit

# otherwise download
# also save youtube id and word hash id to log
id="$(youtube-dl --default-search=auto --get-id "$*")"
echo "$h $id" >> "$HOME/.ytc/lookup_yt.txt"
youtube-dl -o "$HOME/.ytc/$h" -f bestaudio -- "$id"
echo "$h $*" >> "$HOME/.ytc/lookup.txt"

# then play and exit
_play
