#!/bin/bash

[ $# -eq 0 ] && { >&2 echo "usage: $0 <search terms>"; exit 1; }

mkdir -p "$HOME/.ytc"

h="$(md5sum <<< "$*" | cut -d' ' -f1)"

_play() {
    if [ -e "$HOME/.ytc/$h"* ]; then
        mpv --vo=null "$HOME/.ytc/$h"*
        exit
    fi
}

alias silence="&>/dev/null"

prune() {
    pushd "$HOME/.ytc"

    a=""
    for b in *; do
        [ ! -f "$b" ] && continue

        if [ -n "$a" ]; then
            if cmp -s "$a" "$b"; then
                rm "$b"
                ln -sv "$a" "$b"
            fi
        fi

        a="$b"
    done

    popd
}

_play # attempt to play cached file and exit

# otherwise download
# also save youtube id and word hash id to log
id="$(youtube-dl --default-search=auto --get-id "$*")"
echo "$h $id" >> "$HOME/.ytc/lookup_yt.txt"
youtube-dl -o "$HOME/.ytc/$h" -f bestaudio "$id"
echo "$h $*" >> "$HOME/.ytc/lookup.txt"
#prune

# then play and exit
_play
