#!/bin/bash

energy_now=$( cat /sys/class/power_supply/BAT0/energy_now)
energy_full=$(cat /sys/class/power_supply/BAT0/energy_full)
charge=$(echo "scale=2; $energy_now / $energy_full" | bc)

echo "$charge"
