#!/bin/bash
set -e

res="$(xrandr | grep \* | awk '{print $1}' | head -n1)"

ffmpeg -y -f x11grab -video_size "$res" -framerate 30 -i $DISPLAY  \
       -vcodec libx264 -preset ultrafast -qp 0 -pix_fmt yuv444p \
       video.mkv

ffmpeg -y video.mkv video.mp4

rm -v video.mkv
