#!/bin/bash

if [ $# -ne 1 ] && [ $# -ne 2 ]; then
    >&2 echo "usage: $(basename "$0") <url> [output.html]"
    exit 1
fi
url="$1"
out="${2:-index.html}"

cat <<EOF > "$out"
<!doctype html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="refresh" content="0; '$url'">
    <a href="$url">$url</a>
EOF
