#!/bin/bash

if [ "$#" -ne 1 ]; then
    >&2 echo "usage: $(basename "$0") <dataaset>"
    >&2 echo
    >&2 echo "take a snapshot of a zfs dataset."
    exit 1
fi

zfs snapshot $dataset@$(date -I)_$(date +%s)
