#!/bin/bash

if [ "$#" -eq 0 ]; then
    >&2 echo "usage: $(basename "$0") <dataset> [options]"
    >&2 echo
    >&2 echo "take a snapshot of a zfs dataset."
    exit 1
fi

dataset="$1"
shift
rhs="$(date -I)_$(date +%s)"
name="$dataset@$rhs"

[ "$(basename "$0")" == "zsr" ] && recursive="-r"
zfs snapshot $recursive "$name" "$@"

list="$(zfs list -r -t snapshot)"
head -n1    <<< "$list"
grep "$rhs" <<< "$list"
