#!/bin/bash

help_msg() {
    >&$1 echo "Usage: $0 <file.crdownload> <cmd>"
    exit $(($1-1))
}

if [ $# -ne 2 ]; then
    help_msg 2
elif [ "$1" == "--help" ] || [ "$1" == "-h" ]; then
    help_msg 1
fi

file="$1"
cmd="$2"

fin_file="$(sed -e 's/\.crdownload$//g' <<< $file)"
cmd=${cmd/\{\}/$fin_file}

until [ -f $fin_file ]; do
    sleep 1
done

$cmd
