#!/bin/bash
################################################################################
# dwmstatus
#
# Script to generate the statusbar for dwm.
# Author: Ryan Jacobs <ryan.mjacobs@gmail.com>
#
#  May 13, 2014 -> File creation.
#  May 28, 2014 -> Fixed bug that when the battery couldn't be read it crashed.
# July 04, 2014 -> Change name of script to: dwmstatus
# Dec. 14, 2014 -> Notify user when battery is less than 10%.
################################################################################

# Global Constants
WIFI_DEVICE=wlp2s0
REFRESH_DELAY=1

while true; do
    # System Uptime
    DWM_UPTIME=$(simple_uptime) # Custom C binary to output uptime

    # Power/Battery Status
    if [ "$(cat /sys/class/power_supply/AC0/online)" == 1 ]; then
        DWM_BATTERY="AC"
    elif [ "$(cat /sys/class/power_supply/BAT0/energy_now)" -gt 0 ]; then
        percent=$((`cat /sys/class/power_supply/BAT0/energy_now` * 100 /\
                   `cat /sys/class/power_supply/BAT0/energy_full`))
        if [ $percent -lt 10 ]; then
            echo                    "Warning - Low Battery - Less than $DWM_BATTERY% left."
            notify-send -u critical "Warning - Low Battery" "Less than $DWM_BATTERY% left."
        fi
        DWM_BATTERY="$percent%"
    else
        DWM_BATTERY="NULL"
    fi

    # Wi-Fi eSSID
    essid=$(/sbin/iwgetid -r $WIFI_DEVICE)
    if [ ! -z "$essid" ]; then
        strength=$(grep "$WIFI_DEVICE" /proc/net/wireless | awk '{print $3}' | tr -d .)
        DWM_WIFI="$essid [$strength%]"
    else
        DWM_WIFI="OFF"
    fi

    # Volume Level
    DWM_VOL=$(amixer -c0 sget Master | awk -vORS='' '/Mono:/ {print($6$4)}')

    # Date and Time
    DWM_CLOCK=$(date '+%a %b %d, %Y | %r')

    # Overall output command
    DWM_STATUS="Uptime: [$DWM_UPTIME] | WiFi: $DWM_WIFI | Power: [$DWM_BATTERY] | Vol: $DWM_VOL -- $DWM_CLOCK"

    xsetroot -name "$DWM_STATUS"
    sleep $REFRESH_DELAY
done
