#!/bin/bash
################################################################################
# leep 'Lock and Sleep'
#
# This script starts 'slock' and then calls pm-suspend.
#
# Maintained By: Ryan Jacobs <ryan.mjacobs@gmail.com>
#  Last Updated: May 05, 2014
################################################################################
slock &
sudo pm-suspend
