#!/bin/bash
################################################################################
# minecraft_server
#
# Launches a 1.7.9 minecraft server with 2048MB RAM.
#
# Maintained By: Ryan Jacobs <ryan.mjacobs@gmail.com>
#
# April 30, 2014 -> Original creation.
#   May 18, 2014 -> If the server path doesn't exist, then create it.
#                   And, I added a check for the server .jar file.
################################################################################

SERVER_PATH="$HOME/.bin/minecraft_files/minecraft_server"
SERVER_JAR="$SERVER_PATH/minecraft_server.1.7.9.jar"

if [ ! -f "$SERVER_PATH/$SERVER_JAR" ]; then
    printf "The server .jar file doesn't exist!\n"
    printf "We are trying to use '%s'.\n" "$SERVER_PATH/$SERVER_JAR"
    printf "Please go download it and place it in '%s'.\n" "$SERVER_PATH"

pushd "$SERVER_PATH" || (mkdir -p "$SERVER_PATH"; pushd "$SERVER_PATH")
java -Xmx2048M -Xms2048M -jar "$SERVER_PATH/$SERVER_JAR"
popd
