#!/bin/bash
################################################################################
# minecraft_server
#
# Launches a 1.7.9 minecraft server with 2048MB RAM.
#
# Maintained By: Ryan Jacobs <ryan.mjacobs@gmail.com>
# April 30, 2014 -> File creation.
#   May 18, 2014 -> If the server path doesn't exist, then create it.
#                   And, I added a check for the server .jar file.
################################################################################

MINECRAFT_FILES="$HOME/.bin/minecraft_files"
SERVER_PATH="$MINECRAFT_FILES/minecraft_server"
SERVER_JAR="minecraft_server.1.7.9.jar"

if [ ! -f "$MINECRAFT_FILES/$SERVER_JAR" ]; then
    printf "The server .jar file doesn't exist!\n"
    printf "We are trying to use '%s'.\n" "$SERVER_JAR"
    printf "Please go download it into '%s'.\n" "$MINECRAFT_FILES"
    exit 1
fi

if [ ! -d "$SERVER_PATH" ]; then
    mkdir -p "$SERVER_PATH"
fi

cd "$SERVER_PATH" || {
    printf "The path %s doesn't exist.\n" "$SERVER_PATH"
    printf "Creating it...\n"

    mkdir -p "$SERVER_PATH" && printf "Created it!\n" || {
        printf "Failed to create path.\n"
        exit 1
    }
}

cd "$SERVER_PATH"
java -Xmx2048M -Xms2048M -jar "$MINECRAFT_FILES/$SERVER_JAR"
