#!/bin/bash
################################################################################
# .vnc/xstartup
#
# Author: Ryan Jacobs <ryan.mjacobs@gmail.com>
# June 18, 2014 -> File creation.
################################################################################

# Load .Xresources file (without high-DPI scaling)
tmpxr="$(mktemp)"
cp "$HOME/.Xresources" "$tmpxr"
grep -v Xft "$HOME/.Xresources" > "$tmpxr"
xrdb "$tmpxr"
rm "$tmpxr"

# Set the background wallpaper
feh --bg-scale $HOME/.bin/wallpapers/blue_lagoon.jpg &

# Allow clipboard over VNC
vncconfig -iconic &

# Start the WM
termite &
#exec dwm
tint2 &
exec openbox
